export declare const valuesNoLocals: never;
export declare const valuesNoLocals2: never;
export declare const valuesLocalsAreAny: any;
export declare const valuesLocalsAreUnknown: unknown;
export declare const valuesLocalsAreNever: never;
export declare const valuesLocalsAreString: string;
export declare const valuesOneStringValue: string;
export declare const valuesOneStringNumberValue: string | number;
export declare const valuesExact: true | 1;
export declare const valuesSub: true;
export declare const valuesSuper: true | 2 | 1;
